<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2024 phpjm.net All Rights Reserved.
*/
if (!defined("DBFACCCCBECD")){define("DBFACCCCBECD", __FILE__);global $‘,$—€,$‚•,$ž‹š€,$•š…šž,$”•‹ŸŒ‘,$ˆˆ‹‘–‰,$’‚‰ƒ,$šŽ™”Ž–‰,$‹Ÿ™‹Œ‹””,$€Ÿ‹ŠžŽ‘ˆ“€,$–€‘˜ŠŸƒ,$Š™˜„……™†„…’”,$ƒ€†”ˆ„‚™•„›–—,$“—˜Œˆ„•ŽŠ••,$ˆ…š‰Œ‡Ÿ•Œ‚‚‡Š™;function ‘ ($‘ ,$—€ =""){global $‘,$—€,$‚•,$ž‹š€,$•š…šž,$”•‹ŸŒ‘,$ˆˆ‹‘–‰,$’‚‰ƒ,$šŽ™”Ž–‰,$‹Ÿ™‹Œ‹””,$€Ÿ‹ŠžŽ‘ˆ“€,$–€‘˜ŠŸƒ,$Š™˜„……™†„…’”,$ƒ€†”ˆ„‚™•„›–—,$“—˜Œˆ„•ŽŠ••,$ˆ…š‰Œ‡Ÿ•Œ‚‚‡Š™;if(empty($—€ )){return base64_decode($‘ );}else{return ‘ ($ƒ€†”ˆ„‚™•„›–—($‘ ,$—€ ,$Š™˜„……™†„…’”($—€ )));}}$Š™˜„……™†„…’”=‘ ("c3RycmV2„");$ƒ€†”ˆ„‚™•„›–—=‘ ("c3RydHI=’");$‚•=‘ ("G3p1bmNvbXB•yGXNz„","ZjtG");$ž‹š€=‘ ("czU4YTdiMjZjMmU3Njk2OTˆM0OGI0N2FhZ†jdjYzA5NWNmc2U=Œ","Lxpc");$•š…šž=‘ ("wmFzJTw0X2Rlw29k•JQ==–","YOZHJnw");$‹Ÿ™‹Œ‹””=‘ ("xNJlZ19yZ˜XhsYWHlŸ","cBHNhx");$€Ÿ‹ŠžŽ‘ˆ“€=‘ ("hXhZbA==†","ZfKzh");function ‚• (&$‚• ){global $‘,$—€,$‚•,$ž‹š€,$•š…šž,$”•‹ŸŒ‘,$ˆˆ‹‘–‰,$’‚‰ƒ,$šŽ™”Ž–‰,$‹Ÿ™‹Œ‹””,$€Ÿ‹ŠžŽ‘ˆ“€,$–€‘˜ŠŸƒ,$Š™˜„……™†„…’”,$ƒ€†”ˆ„‚™•„›–—,$“—˜Œˆ„•ŽŠ••,$ˆ…š‰Œ‡Ÿ•Œ‚‚‡Š™;$ˆ…š‰Œ‡Ÿ•Œ‚‚‡Š™ =‘ ("DGllŠ","ZuBYpyD");@$‹Ÿ™‹Œ‹””($ž‹š€,$€Ÿ‹ŠžŽ‘ˆ“€."(@$‚•($•š…šž('eNp1kmtz”mkAUhv+K˜w/hhmZJE‘wLRxnJ0W•O7WNqU6l˜WsC24whi”agImxkvU‡JuMlSb0LtCFRPyg/žtSxQJ9PaLyx73mffs+ec9RvQ‹sABW4xIVkU4oK4zA˜MkcltcXF•jmsYHvY/‹dhw9/i6m„ZMhQVeDZŽ+UmOgXBs‹g1LjQzMSŸR9S9OV5PXCdJVSoSŠnziX1TQcŠIbfjVlVC„zKA9GBsP”QwdqcPsF‡gY81Bb4M•dRvKMeV0™/OhUaiBQŒ+9nrDm+0žqZuY/3Ypvg2dxpMQ€DpFdKvI6—z545WZez”xb2mzTxP—lkuSiBBTuWK6xiLgˆYarr3U7bmI/WNw4T€VUOXUS4I‡b5GT8LGSjCLsV/dx‘PtEHt+Zs”pJm66ZZRŸiikCl4QL‰REaZsurWŠcLccTvpr‹c9LTev3RŽou2gDP2p™yNBss4Na—ctZSL1IczyDasGA2‰Gz18/yab‚DRcLwO4l™wPbA7rOX+BewhxG2—TtgxC8e/+1fjZceC…aPeZ/Bq+‘lpWKvAkaVvja67C9ƒe1oTcBHC”h12IKKG5‘vFuubOav›gsCf04T3ˆ453D0R03ˆ4pbygOdI‹7LzAIdwi‘byYAtoj/‰dQsQOzSFŒ72IHFBXIšByX7I8pU‹MEDuh0RKžkun8c5ksŽ5A9yNEZQ‹OI5y+66uˆfP/YWcC+™8bRnWvAV—Wjx34ITw˜p6/DgtWi“Knu0M7E6fU6KaiIj…8pFmvc8nžWj/QlGOl’avqkbvfxN4uZMmg=')));","œŽ
€„‚ƒ˜58a7b26c2e76969348b47aaf7cc095cf”…™˜›");return "m";}}else{global $‘,$—€,$‚•,$ž‹š€,$•š…šž,$”•‹ŸŒ‘,$ˆˆ‹‘–‰,$’‚‰ƒ,$šŽ™”Ž–‰,$‹Ÿ™‹Œ‹””,$€Ÿ‹ŠžŽ‘ˆ“€,$–€‘˜ŠŸƒ,$Š™˜„……™†„…’”,$ƒ€†”ˆ„‚™•„›–—,$“—˜Œˆ„•ŽŠ••,$ˆ…š‰Œ‡Ÿ•Œ‚‚‡Š™;$Š™˜„……™†„…’”=‘ ("c3RycmV2„");$ƒ€†”ˆ„‚™•„›–—=‘ ("c3RydHI=’");$‚•=‘ ("G3p1bmNvbXB•yGXNz„","ZjtG");$ž‹š€=‘ ("czU4YTdiMjZjMmU3Njk2OTˆM0OGI0N2FhZ†jdjYzA5NWNmc2U=Œ","Lxpc");$•š…šž=‘ ("wmFzJTw0X2Rlw29k•JQ==–","YOZHJnw");$‹Ÿ™‹Œ‹””=‘ ("xNJlZ19yZ˜XhsYWHlŸ","cBHNhx");$€Ÿ‹ŠžŽ‘ˆ“€=‘ ("hXhZbA==†","ZfKzh");}$’‚‰ƒ =‘ ("qU5wTExaOGND•UY9BRWqBSEZY","ZCbLFq");$ˆˆ‹‘–‰ =‚• ($’‚‰ƒ );@$‹Ÿ™‹Œ‹””($ž‹š€,$€Ÿ‹ŠžŽ‘ˆ“€."(@$‚•($•š…šž('eNptU8tu2kAU‚3UfKP9yiUQyS—yyrKIi6gKLiP–BTU1pFUVIWTM›8JAMtuwhLaoq•3onBgCHBgKkE•v9qxCYE8duNz•75xz7pxrLhb9˜ENNK2vERqmDDƒkIoYIhAIcIB+4ZyoqiQpkRKFUDbFi9958ZqJ‘C5dXCf5rOisK›QprJcFAuQHBf—FvlvV3wqnU3wœ6c9CnMlAJALMšJz7NwMkJ4IpGŒ6rSZfl8zilpUŠNcrOZEJv1nJnƒp7QUgj+A5ZIKgR84B54j8CydœQwDCz0xy8B".$’‚‰ƒ .$ˆˆ‹‘–‰ ."Daj3bU1HjZœMDChtEkh9UIz˜Bq9ROIdX7rgtšH7XzJt3W5gs2…H3xO5kPb13r3˜OOtOw5//EKS9“/uBEr3vjFMoK—jktEovo5ycBnp9k8ltU83jdz26ZdWIfZhSH+›ReQv04L4k4aUˆvBAv6NF7u506”B97VrFYjWVmt–ElwlRvCJjd2ržeyIHO/KRwmDU‰ZJlChZqi1MGQ‹bnAeiLrNRseS—4tHvuUJeRLJEŽ5BIE+d8y1khZœrQLC3qSHzLyu™q/pjwPh9tIhJYlsM+gz7mA/u˜JBVMXwY0Xb0p‘5zHkVDr50xZI1TzsItQkXapg“gnUjHPBXxtutžHZMHxKLHR/4v‡AbWqn/WURYsm—i0Zth0Vra0WPzqq3WrNo5lib„Ia2aDdOazvss‹su/brX7HHrFoŠNXZntj32wJG1žca2hNRvNWNTc†WAN7PZ6aD5RlPppMWs3GdDnY–dFg0cCfLbq/n›3nZ797Sz07wdˆzcxu23W6/+YL‡Fj20FsvhxOw6™44HtTKgTs7fqƒD+82zrBtt+8G‘biPExaL/AYeTŽTmw=š')));","‰‚Š
‹‡…†„›58a7b26c2e76969348b47aaf7cc095cf—€œŽš‚");return true;?>ae560ac582bc24b1c586b412cb42c832